// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoyalVilla_API.Data;

#nullable disable

namespace RoyalVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430161640_SeedVilla")]
    partial class SeedVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoyalVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            CreatedDate = new DateTime(2026, 4, 30, 17, 16, 38, 770, DateTimeKind.Local).AddTicks(7229),
                            Details = "This is the Royal Villa with stuning ocean view",
                            Name = "Royal Villa",
                            Occupancy = 6,
                            Price = 200m,
                            UpdatedDate = new DateTime(2026, 4, 30, 17, 16, 38, 771, DateTimeKind.Local).AddTicks(9957)
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            CreatedDate = new DateTime(2026, 4, 30, 17, 16, 38, 772, DateTimeKind.Local).AddTicks(693),
                            Details = "This is the Royal Villa with pool and bar view",
                            Name = "Royal Villa",
                            Occupancy = 6,
                            Price = 200m,
                            UpdatedDate = new DateTime(2026, 4, 30, 17, 16, 38, 772, DateTimeKind.Local).AddTicks(697)
                        },
                        new
                        {
                            Id = 3,
                            Color = "White",
                            CreatedDate = new DateTime(2026, 4, 30, 17, 16, 38, 772, DateTimeKind.Local).AddTicks(700),
                            Details = "This is the Royal Villa with pool and bar view",
                            Name = "Royal Villa",
                            Occupancy = 6,
                            Price = 200m,
                            UpdatedDate = new DateTime(2026, 4, 30, 17, 16, 38, 772, DateTimeKind.Local).AddTicks(701)
                        },
                        new
                        {
                            Id = 4,
                            Color = "Green",
                            CreatedDate = new DateTime(2026, 4, 30, 17, 16, 38, 772, DateTimeKind.Local).AddTicks(705),
                            Details = "This is the Royal Villa with football feild and view",
                            Name = "Royal Villa",
                            Occupancy = 6,
                            Price = 200m,
                            UpdatedDate = new DateTime(2026, 4, 30, 17, 16, 38, 772, DateTimeKind.Local).AddTicks(706)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
